pipeline:
  identifier: Build_new_repo_1683635912360
  name: Build new_repo
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1683635774997
        repoName: eshah-crest/new_repo
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
    - parallel:
        - stage:
            name: CD
            identifier: CD
            description: ""
            type: Deployment
            spec:
              deploymentType: Kubernetes
              service:
                serviceRef: Service1
              environment:
                environmentRef: Env1
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: Infra1
              execution:
                steps:
                  - step:
                      type: K8sDryRun
                      name: K8sDryRun_1
                      identifier: K8sDryRun_1
                      spec: {}
                      timeout: 10m
                rollbackSteps: []
            tags: {}
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: StageRollback
        - stage:
            name: CD2
            identifier: CD2
            description: ""
            type: Deployment
            spec:
              deploymentType: Kubernetes
              service:
                serviceRef: Service1
              environment:
                environmentRef: Env1
                deployToAll: false
                infrastructureDefinitions:
                  - identifier: Infra1
              execution:
                steps:
                  - step:
                      type: K8sDryRun
                      name: K8sDryRun_1
                      identifier: K8sDryRun_1
                      spec: {}
                      timeout: 10m
                rollbackSteps: []
            tags: {}
            failureStrategies:
              - onFailure:
                  errors:
                    - AllErrors
                  action:
                    type: StageRollback
